version: '2.1'

services:
  ibole_vue_ssr_platform:
    image: ibole_vue_ssr_platform
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
      - 9229:9229
    ## set your startup file here
    command: node --inspect index.js